url=https://api.nicmid.com/apiv1/motor_policies/
url.Branch=https://api.nicmid.com/apiv1/branches/
url.UserName=millennium
url.Password=vuPtzNns
url.Token=E8rZHBDF38xuQobQWeYD7tL2
GX.1 = PRIVATE_INDIVIDUAL_X1
GX.1E = PRIVATE_INDIVIDUAL_X1
GX.4 = PRIVATE_CORPORATE_X4
GX.4E = PRIVATE_CORPORATE_X4
GZ.405 = TAXI
GZ.405E = TAXI
GY.3 = MOTOR_CYCLE
GY.3E = MOTOR_CYCLE
GZ.300 = OWN_GOODS_SMALL
GZ.300E = OWN_GOODS_SMALL
GZ.301 = ZART_TANKERS
GZ.301E = ZART_TANKERS
GZ.405T = GEN_CARTAGE_SMALL
GZ.802 = Z802_ONSITE
GZ.802E = Z802_ONSITE
GW.1 = GW1_CLASS1
GW.1E = GW1_CLASS1
