strNCB = NCD
strFRB =FLD
strODBA = BASE
strTPBA = TPP
strESLO = ESL
strPA = PA
strZECP = EP
strCCLO = ""
strIDL = ""
strOA = ""
strEBB = EXL
strZTPP = "ETPD"
strZRPL = AP
strNCB2 = NCD2
strFRB2 = FLD2
strODBA2 = BAS2
strTPBA2 = TPP2
strESLO2 = ESL2
strPA2 = PA2
strZECP2 = EP2
strCCLO2 = ""
strIDL2 = ""
strOA2 = ""
strEBB2= EXL2
strZTPP2 = ET3
strZRPL2 = AP2
STICKER_FEE = 33
PERSONAL_ACCIDENT_CHARGE = 20
BROWN_CARD_FEE = 10
TPPD_LIMIT = TP