url=https://liveapi.nicmid.com/apiv1/motor_policies/
url.Branch=https://liveapi.nicmid.com/apiv1/branches/
url.UserName=PRIMEINSAPI
url.Password=xbgEilVN
url.Token=7EL9RQmceNupsrEPJuX9Frea
X1-TP=PRIVATE_INDIVIDUAL_X1
X1CFC=PRIVATE_INDIVIDUAL_X1
X1CFCN=PRIVATE_INDIVIDUAL_X1
X1COMP=PRIVATE_INDIVIDUAL_X1
Y3-CFC=MOTOR_CYCLE
Y3-CFN=MOTOR_CYCLE
Y3-COMP=MOTOR_CYCLE
Y3/100C=MOTOR_CYCLE
Y3/100CF=MOTOR_CYCLE
Y3/100T=MOTOR_CYCLE
Z300-TP=OWN_GOODS_SMALL
>Z300-TP=OWN_GOODS_LARGE
Z300-CFC=OWN_GOODS_SMALL
Z300-CFN=OWN_GOODS_SMALL
Z300CFN=OWN_GOODS_SMALL
>Z300-CFC=OWN_GOODS_LARGE
>Z300-CFN=OWN_GOODS_LARGE
>Z300CFN=OWN_GOODS_LARGE
Z300-TP=OWN_GOODS_SMALL
>Z300-TP=OWN_GOODS_LARGE
Z300-COM=OWN_GOODS_SMALL
>Z300-COM=OWN_GOODS_LARGE
Z300COM=OWN_GOODS_SMALL
>Z300COM=OWN_GOODS_LARGE
Z301=GEN_CARTAGE_LARGE
>Z301=GEN_CARTAGE_LARGE
Z301AT=ART_TANKERS
Z301TPAT=ART_TANKERS
Z301-TP=GEN_CARTAGE_SMALL
>Z301-TP=GEN_CARTAGE_LARGE
Z301-TPAT=ART_TANKERS
Z301CFC=GEN_CARTAGE_SMALL
>Z301CFC=GEN_CARTAGE_LARGE
Z301CFCA=ART_TANKERS
Z301CFN=GEN_CARTAGE_SMALL
>Z301CFN=GEN_CARTAGE_LARGE
Z301CFNA=ART_TANKERS
Z405-TTX=TAXI
Z405-CMB=MINI_BUS
Z405-CHR=HIRING_CARS
Z405-CMAB=MAXI_BUS
Z405-TTX=TAXI
Z405-TMB=MINI_BUS
Z405-THR=HIRING_CARS
Z405-TMAB=MAXI_BUS
Z405-TTX=TAXI
Z405CFCM=MINI_BUS
Z405CFCH=HIRING_CARS
Z405CFCX=MAXI_BUS
Z405-CTX=MINI_BUS
Z405-TTX=TAXI
Z405CFNM=MINI_BUS
Z405CFNH=HIRING_CARS
Z405CFNX=MAXI_BUS
Z405TMAB=MAXI_BUS
Z802CFC=Z802_ONSITE
Z802CFCR=Z802_ONROAD
Z802CFN=Z802_ONSITE
Z802CFNR=Z802_ONROAD
Z802-C=Z802_ONSITE
Z802-CR=Z802_ONROAD
Z802-TP=Z802_ONSITE
Z802-TPR=Z802_ONROAD
X4-TP=PRIVATE_CORPORATE_X4
X4CFC=PRIVATE_CORPORATE_X4
X4CFCN=PRIVATE_CORPORATE_X4
X4COMP=PRIVATE_CORPORATE_X4
Y3-TP=MOTOR_CYCLE
GW1=GW1_CLASS1