GW1=W.1.1CLASS
X1-TP=X.1PRIVATEINDIVIDUAL
X1-C-FC=X.1PRIVATEINDIVIDUAL
X1-C-FCN=X.1PRIVATEINDIVIDUAL
X1-COMP=X.1PRIVATEINDIVIDUAL
Y3-C-FC=Y.3MOTORCYCLE
Y3-C-FCN=Y.3MOTORCYCLE
Y3-COMP=Y.3MOTORCYCLE
Y3/100C=Y.3MOTORCYCLE
Y3/100CF=Y.3MOTORCYCLE
Y3/100T=Y.3MOTORCYCLE
Z300-TP=Z.300OWNGOODSUPTO3000CC
>Z300-TP=Z.300OWNGOODSABOVE3000CC
Z300-CFC=Z.300OWNGOODSUPTO3000CC
>Z300-CFC =Z.300OWNGOODSABOVE3000CC
Z300-CFN=Z.300OWNGOODSUPTO3000CC
>Z300-CFN=Z.300OWNGOODSABOVE3000CC
Z300-COM=Z.300OWNGOODSUPTO3000CC
>Z300-COM=Z.300OWNGOODSABOVE3000CC
Z301=Z.301GEN.CARTAGEUPTO3000CC
>Z301=Z.301GEN.CARTAGEABOVE3000CC
Z301AT=Z.301ARTTANKERS
Z301-TP=Z.301GEN.CARTAGEUPTO3000CC
>Z301-TP=Z.301GEN.CARTAGEABOVE3000CC
Z301-TPAT=Z.301ARTTANKERS
Z301CFC=Z.301GEN.CARTAGEUPTO3000CC
>Z301CFC=Z.300GEN.CARTAGEABOVE3000CC
Z301CFCA=Z.301ARTTANKERS
Z301CFN=Z.301GEN.CARTAGEUPTO3000CC
>Z301CFN=Z.301GEN.CARTAGEABOVE3000CC
Z301CFNA=Z.301ARTTANKERS
Z405-CTX=Z.405TAXI
Z405-CMB=Z.405MINIBUS
Z405-CHR=Z.405HIRINGCARS
Z405-CMAB=Z.405MAXIBUS
Z405-TTX=Z.405TAXI
Z405-TMB=Z.405MINIBUS
Z405-THR=Z.405HIRINGCARS
Z405-TMAB=Z.405MAXIBUS
Z405CFCT=Z.405TAXI
Z405CFCM=Z.405MINIBUS
Z405CFCH=Z.405HIRINGCARS
Z405CFCX=Z.405MAXIBUS
Z405CFNT=Z.405TAXI
Z405CFNM=Z.405MINIBUS
Z405CFNH=Z.405HIRINGBUS
Z405CFNX=Z.405MAXIBUS
Z802-CFC=Z.802ONSITE
Z802CFCR=Z.802ONROAD
Z802-CFN=Z.802ONSITE
Z802CFNR=Z.802ONROAD
Z802-C=Z.802ONSITE
Z802-CR=Z.802ONROAD
Z802-TP=Z.802ONSITE
Z802-TPR=Z.802ONROAD
X4-TP=X.4PRIVATECORPORATE
X4-C-FC=X.4PRIVATECORPORATE
X4-C-FCN=X.4PRIVATECORPORATE
X4-COMP=X.4PRIVATECORPORATE
Y3-TP=Y.3MOTORCYCLE