url.Live=https://liveapi.nicmid.com/apiv1/motor_policies/
url.Test=https://api.nicmid.com/apiv1/motor_policies/
url.BranchLive=https://liveapi.nicmid.com/apiv1/branches/
url.BranchTest=https://api.nicmid.com/apiv1/branches/
url.PrimeTestUserName=PRIMEINSAPI
url.PrimeTestPassword=KINqVawp
url.PrimeTestToken=ibWgwpjQEZ1RW8G5318EN3eG
url.PrimeLiveUserName=PRIMEINSAPI
url.PrimeLivePassword=xbgEilVN
url.PrimeLiveToken=7EL9RQmceNupsrEPJuX9Frea
url.MilleniumTestUserName=millennium
url.MilleniumTestPassword=vuPtzNns
url.MilleniumTestToken=E8rZHBDF38xuQobQWeYD7tL2
url.MilleniumLiveUserName=odyssey
url.MilleniumLivePassword=brXLMiXE
url.MilleniumLiveToken=h2pE7R23ZY72WGUSqnvQnL5Y