url=https://api.midv2.nicgh.com
url.Branch=https://api.nicmid.com/apiv1/branches/
url.policies=https://api.midv2.nicgh.com/api/policies
url.UserName=jbanda@insurefin.com
url.Password=@M1llenn1uMInsurance
url.x-api-key =41e5e8cf3b3441b198ebf5723425a156
GX.1 = X.1PRIVATEINDIVIDUAL
GX.1E = X.1PRIVATEINDIVIDUAL
GX.4 = X.4PRIVATECORPORATE
GX.4E = X.4PRIVATECORPORATE
GZ.405 = Z.405TAXI
GZ.405E = Z.405TAXI
GY.3 = Y.3MOTORCYCLE
GY.3E = Y.3MOTORCYCLE
GZ.300 = Z.300OWNGOODSUPTO3000CC
GZ.300E = Z.300OWNGOODSUPTO3000CC
GZ.301 = Z.301ARTTANKERS
GZ.301E = Z.301ARTTANKERS
GZ.405T = Z.301GENCARTAGETUPTO3000CC
GZ.802 = Z.802ONSITE
GZ.802E = Z.802ONSITE
GW.1 = W.1.1CLASS
GW.1E = W.1.1CLASS
